### ISSUE TITLE
Inline loading for Cryo-Archive view

### ISSUE THREAD

**Issue by MaxAldejohann** [markusrt/NRZMyk#108]
when u hit the button indicating kryo perservation of a sample the page jumps back to the very top. so u have to scroll down again 4 each sample, which may be very time consuming given a usual a high number of isolates.  maybe there is a fix for that? e.g. maybe it is more easy to checkbox the isolates first and than hit the button kryo- preservation for all? what u think @markusrt ?

**Comment by markusrt** [comment]
Hi Max, I agree that this is not ideal. As you already proposed we either do it via checkbox or without reloading/jumping back to the top.

Ideally the latter solution is even easier. I put it on the backlog to be adressed once the other open issues are done 👍

**Comment by markusrt** [comment]
@MaxAldejohann this enhancement is now available on staging system. Please take a look and do some tests there 🧪

**Comment by MaxAldejohann** [comment]
@markusrt good job! Seems fine 2 me

**Comment by markusrt** [comment]
Thanks for the feedback. Done and closed 😃
