### ISSUE TITLE
Timeout on export

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMyk#130]
Export runs into a client-side timeout. Swagger works and returns after ~3 minutes

For now, it should be enough to increase the HTTP client timeout. A better solution for later would probably be to send export via E-Mail once ready.

**Comment by markusrt** [comment]
@MaxAldejohann This issue is fixed with today's release [v.1.0.2211.2711](https://github.com/markusrt/NRZMyk/releases/tag/v.1.0.2211.2711). The error was caused by a timeout as the amount of data is increasing on the export.

Now the export should finish successful after ~ 3 minutes.

**Comment by MaxAldejohann** [comment]
@markusrt  test was successful! Bug fixed 🥇
