### ISSUE TITLE
Wrong resistance for c. krusei

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMyk#131]
C. krusei is treated as resistant for Anidulafungin with a MIC value of 0.06. This should still be sensitive, only > 0.06 would be treated as resistant.

- [x] Values are always normalized to the reference method prior to resistance evaluation
- [x] Existing data is cleaned accordingly

**Comment by markusrt** [comment]
@MaxAldejohann: I tried to reproduce the issue but did not find the combination where it is wrong.

E.g. that's what we have now
<img width="671" alt="image" src="https://user-images.githubusercontent.com/299753/203860826-d27036ec-e784-47b4-96ff-b5cad56fba1f.png">

Did you refer to the E-Test value where 0.064 is treated as resistent instead of sensitive?

**Comment by MaxAldejohann** [comment]
@markusrt exactely! though etest has its own range of MIC-values (as shown in the pic), this technique is always compared with and evaluated by the MIC ranges of the ref methode broth microdilution. therefore only 0.06 and 0.125 do matter as endpoints of the readout and serve for a breakpoint evaluation. Everything in between these values do not exsist in the ref methode. that is why if these strains do not reach the next MIC of 0.125 they have to be evaluated as susceptible. this means 0,064 is susceptible. its a bit confusing :) 
![AnidulafunginEtst](https://user-images.githubusercontent.com/65395238/203956303-7123d458-0999-4ff3-9353-604522569a3f.jpg)

**Comment by markusrt** [comment]
Ok @MaxAldejohann , understood 👍 

Then I have one follow up question. In issue #2 we took [clinical-breakpoints.xls](https://github.com/markusrt/NRZMyk/files/5029312/clinical-breakpoints.xlsx) as input.

There are several entries where >0.06 is the breakpoint. Should these then all be treated as >0.064?
Are there other ambiguous values?

**Comment by MaxAldejohann** [comment]
@markusrt in the end the value of 0.064 should be interpreted as 0.06. When a breakpoint is set as >0.06, 0.06 and 0.064 should be reported as susceptible.

**Comment by markusrt** [comment]
@MaxAldejohann I tried to tackle this with a generic solution, i.e. not specific to 0.064/0.06.

I added a new configuration for a list of reference method values:

```json
"ReferenceMethodMicValues": [ 
    0.002, 0.004, 0.008, 0.016, 0.03, 0.06, 0.12, 0.25, 0.5, 1, 2, 4, 8, 16, 32, 64, 128, 256, 256.001
]
``´

Whenever a MIC step is selected the value is "floored" to the closest ref value. E.g.:
![image](https://user-images.githubusercontent.com/299753/215263892-91f3d05b-e20e-447a-95ec-5d7d7f315dc9.png)
![image](https://user-images.githubusercontent.com/299753/215263905-87467d59-d651-4ef1-ab95-2c777da3f872.png)
![image](https://user-images.githubusercontent.com/299753/215263917-13d20648-c54b-4ad1-b8b3-f4e8dd265a16.png)

As you see for the given example it now only treats 0.125 as resistent.

Question:

- Is it ok to perform this reference method flooring during evaluation for every value? This would now always happen before a decision regarding susceptible, intermediate, or resistant is done
- Is there only one reference list (as done above) or is the reference list dependent on the standard (CLSI, EUCAST)? 
- Is the reference list above complete or am I missing values at the lower or upper end?

**Comment by markusrt** [comment]
Closing during cleanup as it's already implemented and tested.
