### ISSUE TITLE
Kryo-Storage View

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMyk#43]
- [x] Internal view on SuperUser level which lists all sentinel entries
- [x] Filter data by organization
- [x] Sorted by date (newest first)
- [x] Each row has a button/switch cryo Yes/No if flipped to yes a corresponding cryo asservation date is set or unset
- [x]  Only colums for Sentinel Number, Lab Number, and Cryobox Number are shown
- [x]  An entry once stored in a cryo box must not be deleted. I.e. the delete button is removed and a server side check is in place
- [x]  An entry once stored in a cryo box must not be update. I.e. sending laboratories can only show existing data

**Comment by markusrt** [comment]
@SabrinaMue @MaxAldejohann 

I spent some thoughts about how the Kryo-View should work

- Input field allows lab assistant to search for the sender laboratory number
- Result is a list of matching records, could also be just one in case of an exact match
- Each list entry has a button to mark the sentinel record as stored (also setting the current date)

**Question**: Should sending laboratories be allowed to later edit a sending which is marked as stored?

**Comment by MaxAldejohann** [comment]
sounds fine to us. i guess they should not be able to do so.
