### ISSUE TITLE
HospitalDepartmentType.NormalUnit -> HospitalDepartment.Internal allows to enter a third dimension

### ISSUE THREAD

**Issue by markusrt** [markusrt/NRZMyk#93]
When a user selects "Normalstation->internistisch" there should be a possibility to specify the kind of internal station on one more level

Missing input:
@MaxAldejohann will provide a list of possible values

- [x] Existing data defaults to "Other" for this case
- [x] Dropdown appears where user can select a third dimension for internal department

**Comment by MaxAldejohann** [comment]
@markusrt I would include (in that order): 
-hämatoonkologisch
-gastroenterologisch
-infektiologisch
-pulmologisch
-kardiologisch
-endokrinologisch
-nephrologisch
-angiologisch
-rheumatologisch

**Comment by markusrt** [comment]
@MaxAldejohann this enhancement is now available on staging system. Please take a look and do some tests there 🧪

**Comment by MaxAldejohann** [comment]
@markusrt please add "unbekannt" to the panel. Otherwise ok 👍

**Comment by markusrt** [comment]
Closing during cleanup as it's already implemented.
